export { default as CategorieTable } from './CategorieTable'
export { default as UserTable } from './UserTable'
export { default as MailTable } from './MailTable'
export { default as ProductTable } from './ProductTable'
export { default as OrdersTable } from './OrdersTable'
export { default as MainPage } from './MainPage'