export { fetchCategories, addCategorie, editCategorie, deleteCategorie } from './categoryActions'
export { fetchMails, deleteSelectedMails } from './mailActions'
export { fetchUsers, singIn, getAccesCode, deleteSelectedUsers, adminAccept } from './userActions'
export { fetchProducts, fetchProductById, addProduct, editProduct, deleteProduct } from './productActions'
export { fetchOrders, acceptOrder, deleteOrder} from './orderActions'
export { fetchNews, fetchNewsById, addNews, editNews, deleteNews } from './newsActions'