export { fetchCategoriesApi, addCategorieApi, editCategorieApi, deleteCategorieApi} from './CategoryApi'
export { fetchMailsApi, deleteSelectedMailsApi } from './MailsApi'
export { fetchUserApi, deleteSelectedUsersApi, acceptCodeApi, singInApi, adminAcceptApi } from './UsersApi'
export { fetchProductsApi, addProductApi, editProductApi, deleteProductApi } from './ProductsApi'
export { fetchOrdersApi, acceptOrderApi, deleteOrderApi } from './OrdersApi'