//-------------------------------------------------------- Categorie Actions
export const GET_CATEGORIES_START = 'GET_CATEGORIES_START'
export const GET_CATEGORIES_SUCCCES = 'GET_CATEGORIES_SUCCES'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const ADD_CATEGORIE_START = 'ADD_CATEGORIE_START'
export const ADD_CATEGORIE_SUCCES = 'ADD_CATEGORIE_SUCCES'
export const ADD_CATEGORIE_FAILURE = 'ADD_CATEGORIE_FAILURE'

export const EDIT_CATEGORIE_START = 'EDIT_CATEGORIE_START'
export const EDIT_CATEGORIE_SUCCES = 'EDIT_CATEGORIE_SUCCES'
export const EDIT_CATEGORIE_FAILURE = 'EDIT_CATEGORIE_FAILURE'

export const DELETE_CATEGORIE_START = 'DELETE_CATEGORIE_START'
export const DELETE_CATEGORIE_SUCCES = 'DELETE_CATEGORIE_SUCCES'
export const DELETE_CATEGORIE_FAILURE = 'DELETE_CATEGORIE_FAILURE'

//--------------------------------------------------------- Mail Actions
export const GET_MAIL_START = 'GET_MAIL_START'
export const GET_MAIL_SUCCES = 'GET_MAIL_SUCCES'
export const GET_MAIL_FAILURE = 'GET_MAIL_FAILURE'

export const DELETE_MAIL_START = 'DELETE_MAIL_START'
export const DELETE_MAIL_SUCCES = 'DELETE_MAIL_SUCCES'
export const DELETE_MAIL_FAILURE = 'DELETE_MAIL_FAILURE'

//---------------------------------------------------------- User Actions

export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCES = 'GET_USERS_SUCCES'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const DELETE_USERS_START = 'DELETE_USERS_START'
export const DELETE_USERS_SUCCES = 'DELETE_USERS_SUCCES'
export const DELETE_USERS_FAILURE = 'DELETE_USERS_FAILURE'

//----------------------------------------------------------- Product Actions
export const GET_PRODUCT_START = 'GET_PRODUCT_START'
export const GET_PRODUCT_SUCCES = 'GET_PRODUCT_SUCCES'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START'
export const DELETE_PRODUCT_SUCCES = 'DELETE_PRODUCT_SUCCES'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'