export const GET_CATEGORIES_START = 'GET_CATEGORIES_START'
export const GET_CATEGORIES_SUCCCES = 'GET_CATEGORIES_SUCCES'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const ADD_CATEGORIE_START = 'ADD_CATEGORIE_START'
export const ADD_CATEGORIE_SUCCES = 'ADD_CATEGORIE_SUCCES'
export const ADD_CATEGORIE_FAILURE = 'ADD_CATEGORIE_FAILURE'

export const EDIT_CATEGORIE = 'EDIT_CATEGORIE'


export const DELETE_CATEGORIE_START = 'DELETE_CATEGORIE_START'
export const DELETE_CATEGORIE_SUCCES = 'DELETE_CATEGORIE_SUCCES'
export const DELETE_CATEGORIE_FAILURE = 'DELETE_CATEGORIE_FAILURE'