//-------------------------------------------------------- Categorie Actions
export const GET_CATEGORIES_START = 'GET_CATEGORIES_START'
export const GET_CATEGORIES_SUCCCES = 'GET_CATEGORIES_SUCCES'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const ADD_CATEGORIE_START = 'ADD_CATEGORIE_START'
export const ADD_CATEGORIE_SUCCES = 'ADD_CATEGORIE_SUCCES'
export const ADD_CATEGORIE_FAILURE = 'ADD_CATEGORIE_FAILURE'

export const EDIT_CATEGORIE_START = 'EDIT_CATEGORIE_START'
export const EDIT_CATEGORIE_SUCCES = 'EDIT_CATEGORIE_SUCCES'
export const EDIT_CATEGORIE_FAILURE = 'EDIT_CATEGORIE_FAILURE'

export const DELETE_CATEGORIE_START = 'DELETE_CATEGORIE_START'
export const DELETE_CATEGORIE_SUCCES = 'DELETE_CATEGORIE_SUCCES'
export const DELETE_CATEGORIE_FAILURE = 'DELETE_CATEGORIE_FAILURE'

//--------------------------------------------------------- Mail Actions
export const GET_MAIL_START = 'GET_MAIL_START'
export const GET_MAIL_SUCCES = 'GET_MAIL_SUCCES'
export const GET_MAIL_FAILURE = 'GET_MAIL_FAILURE'

export const DELETE_MAIL_START = 'DELETE_MAIL_START'
export const DELETE_MAIL_SUCCES = 'DELETE_MAIL_SUCCES'
export const DELETE_MAIL_FAILURE = 'DELETE_MAIL_FAILURE'

//---------------------------------------------------------- User Actions

export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCES = 'GET_USERS_SUCCES'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const GET_ACCES_CODE_START = 'GET_ACCES_CODE_START'
export const GET_ACCES_CODE_SUCCES = 'GET_ACCES_CODE_SUCCES'
export const GET_ACCES_CODE_FAILURE = 'GET_ACCES_CODE_FAILURE'

export const SING_IN_START = 'SING_IN_START'
export const SING_IN_SUCCES = 'SING_IN_SUCCES'
export const SING_IN_FAILURE = 'SING_IN_FAILURE'

export const ADMIN_ACCEPT_START = 'ADMIN_ACCEPT_START'
export const ADMIN_ACCEPT_SUCCES = 'ADMIN_ACCEPT_SUCCES'
export const ADMIN_ACCEPT_FAILURE = 'ADMIN_ACCEPT_FAILURE'

export const DELETE_USERS_START = 'DELETE_USERS_START'
export const DELETE_USERS_SUCCES = 'DELETE_USERS_SUCCES'
export const DELETE_USERS_FAILURE = 'DELETE_USERS_FAILURE'

//----------------------------------------------------------- Product Actions
export const GET_PRODUCT_START = 'GET_PRODUCT_START'
export const GET_PRODUCT_SUCCES = 'GET_PRODUCT_SUCCES'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'

export const GET_PRODUCT_BY_ID_START = 'GET_PRODUCT_BY_ID_START'
export const GET_PRODUCT_BY_ID_SUCCES = 'GET_PRODUCT_BY_ID_SUCCES'
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE'

export const ADD_PRODUCT_START = 'ADD_PRODUCT_START'
export const ADD_PRODUCT_SUCCES = 'ADD_PRODUCT_SUCCES'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

export const EDIT_PRODUCT_START = 'EDIT_PRODUCT_START'
export const EDIT_PRODUCT_SUCCES = 'EDIT_PRODUCT_SUCCES'
export const EDIT_PRODUCT_FAILURE = 'EDIT_PRODUCT_FAILURE'

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START'
export const DELETE_PRODUCT_SUCCES = 'DELETE_PRODUCT_SUCCES'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'

//------------------------------------------------------------ Orders Actions
export const GET_ORDERS_START = 'GET_ORDERS_START'
export const GET_ORDERS_SUCCES = 'GET_ORDERS_SUCCES'
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE'

export const ACCEPT_ORDERS_START = 'ACCEPT_ORDERS_START'
export const ACCEPT_ORDERS_SUCCES = 'ACCEPT_ORDERS_SUCCES'
export const ACCEPT_ORDERS_FAILURE = 'ACCEPT_ORDERS_FAILURE'

export const DELETE_ORDERS_START = 'DELETE_ORDERS_START'
export const DELETE_ORDERS_SUCCES = 'DELETE_ORDERS_SUCCES'
export const DELETE_ORDERS_FAILURE = 'DELETE_ORDERS_FAILURE'


//-------------------------------------------------------------- News Actions


export const GET_NEWS_START = 'GET_NEWS_START'
export const GET_NEWS_SUCCES = 'GET_NEWS_SUCCES'
export const GET_NEWS_FAILURE = 'GET_NEWS_FAILURE'

export const GET_NEWS_BY_ID_START = 'GET_NEWS_BY_ID_START'
export const GET_NEWS_BY_ID_SUCCES = 'GET_NEWS_BY_ID_SUCCES'
export const GET_NEWS_BY_ID_FAILURE = 'GET_NEWS_BY_ID_FAILURE'

export const ADD_NEWS_START = 'ADD_NEWS_START'
export const ADD_NEWS_SUCCES = 'ADD_NEWS_SUCCES'
export const ADD_NEWS_FAILURE = 'ADD_NEWS_FAILURE'

export const EDIT_NEWS_START = 'EDIT_NEWS_START'
export const EDIT_NEWS_SUCCES = 'EDIT_NEWS_SUCCES'
export const EDIT_NEWS_FAILURE = 'EDIT_NEWS_FAILURE'

export const DELETE_NEWS_START = 'DELETE_NEWS_START'
export const DELETE_NEWS_SUCCES = 'DELETE_NEWS_SUCCES'
export const DELETE_NEWS_FAILURE = 'DELETE_NEWS_FAILURE'

